export const tokens = {
  colors: {
    bgPrimary: "var(--color-bg-primary)",
    bgSecondary: "var(--color-bg-secondary)",
    bgCard: "var(--color-bg-card)",
    textPrimary: "var(--color-text-primary)",
    textSecondary: "var(--color-text-secondary)",
    textMuted: "var(--color-text-muted)",
    accentGreen: "var(--color-accent-green)",
    accentPurple: "var(--color-accent-purple)",
    accentPink: "var(--color-accent-pink)",
    accentAmber: "var(--color-accent-amber)",
    borderPrimary: "var(--color-border-primary)",
    borderAccent: "var(--color-border-accent)",
  },
  spacing: {
    xs: "0.25rem",
    sm: "0.5rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    xxl: "3rem",
    xxxl: "5rem",
  },
  radius: {
    sm: "0.375rem",
    md: "0.75rem",
    lg: "1.25rem",
    xl: "1.75rem",
    full: "9999px",
  },
  font: {
    xs:   "clamp(0.65rem, 1vw,   0.7rem)",
    sm:   "clamp(0.7rem,  1.2vw, 0.8rem)",
    md:   "clamp(0.8rem,  1.5vw, 0.9rem)",
    lg:   "clamp(0.9rem,  1.8vw, 1.05rem)",
    xl:   "clamp(1.1rem,  2.2vw, 1.4rem)",
    xxl:  "clamp(1.4rem,  3vw,   2rem)",
    hero: "clamp(1.8rem,  4vw,   3.2rem)",
    mono: "var(--font-mono)",
  },
  transition: {
    fast:   "150ms ease-out",
    base:   "250ms ease-out",
    slow:   "400ms ease-out",
    spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
  },
} as const;