export const tokens = {
  colors: {
    bgPrimary: "var(--color-bg-primary)",
    bgSecondary: "var(--color-bg-secondary)",
    bgCard: "var(--color-bg-card)",
    textPrimary: "var(--color-text-primary)",
    textSecondary: "var(--color-text-secondary)",
    textMuted: "var(--color-text-muted)",
    accentGreen: "var(--color-accent-green)",
    accentPurple: "var(--color-accent-purple)",
    accentPink: "var(--color-accent-pink)",
    accentAmber: "var(--color-accent-amber)",
    borderPrimary: "var(--color-border-primary)",
    borderAccent: "var(--color-border-accent)",
  },
  spacing: {
    xs: "0.25rem",
    sm: "0.5rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    xxl: "3rem",
    xxxl: "5rem",
  },
  radius: {
    sm: "0.375rem",
    md: "0.75rem",
    lg: "1.25rem",
    xl: "1.75rem",
    full: "9999px",
  },
  font: {
    xs:   "clamp(0.7rem,  1.2vw, 0.75rem)",
    sm:   "clamp(0.75rem, 1.5vw, 0.875rem)",
    md:   "clamp(0.875rem,2vw,   1rem)",
    lg:   "clamp(1rem,    2.5vw, 1.25rem)",
    xl:   "clamp(1.25rem, 3vw,   1.75rem)",
    xxl:  "clamp(1.75rem, 4vw,   2.5rem)",
    hero: "clamp(2.5rem,  6vw,   4.5rem)",
  },
  transition: {
    fast:   "150ms ease-out",
    base:   "250ms ease-out",
    slow:   "400ms ease-out",
    spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
  },
} as const;